ikemen-engine/Ikemen-GO

get.cmd, get.sh, src/sound.go, src/system.go
Vorbis music files are already working, but compared with mp3 and flac it has a different aproach at code level. I've changed it to use faiface/beep so all music formats can be handled the same way.
No idea what Normalizer does tho.
=> Vorbis dependency changed to faiface/beep

script/options.lua, src/main.go, src/render.go, src/system.go
Right now only hqx2 and hqx4 are implemented.
=> HQ filters

build/get.cmd, build/get.sh, src/image.go, src/input.go, src/system.go
This reverts commit beceb136307e1cda590a1265ba42b9d58d163ab0.
=> Revert "Added Screenshots"

script/main.lua
New functions:
- unpack(table) : Modified version of the unpack function that goes through all variables in table with either string or number names.
- text:create({values}) : creates text with values inside the argument table, returns table with all arg values and ti (textimage), as well as other text functions
- text:update({updates}) : Changes all values with those that are put into the argument table.
- text:draw() : Just textImgDraw but shorter
Example:
`local timg = text:create({text="Example"}) -- create text with default values except for text`
`timg:update({text="Ex2"}) -- change the text in timg to Ex2`
`timg:draw() -- draws timg (duh)`
=> Easier to update text

external/script/main.lua
fix for https://github.com/Windblade-GR01/Ikemen_GO/issues/92
=> fixed random stage param

src/common.go, src/compiler.go, src/main.go
-Added comments to main(), Compiler.Compile(), and Compiler.stateCompile() documenting their functionality
-Refactored processCommandLine() and setupConfig() out of main() for readability
=> Documentation Comments - main and compiler

src/script.go, src/system.go
-Added comments to System.fight() and the externalized Lua function game() documenting their functionality
=> Documentation Comments - fight

src/lifebar.go
This will fix Issue 259, the additional argument in the IF statement had been dropped off.
=> Fix for Issue 259

src/system.go
Also move some code out of the innermost loop where possible.
=> Fix a scaling-related discrepancy in collision detection. Addresses #476

src/main.go, src/system.go
This takes the audio closing logic out of main.go
=> Introduce sys.shutdown() for symmetry with sys.init()

src/bytecode.go, src/char.go, src/script.go, src/sound.go, src/system.go
This removes a lot of handmade code that is already available under wav.Decode()
and the beep.Buffer data structure.
=> Use the beep library to parse and decode WAV data

go.mod, go.sum, src/char.go, src/image.go, src/render.go
These various changes help make the OpenGL codebase WebGL-friendly for #485.
=> OpenGL code cleanup

src/char.go
下記の問題、及びダウン時のハードコード処理でMUGENと異なる動作の修正。
https://mugenguild.com/forum/topics/ground-bounce-behaviour-different-mugen-ikemen-179029.0.html
・ダウン時に攻撃を受けたとき、pos yが0以外だとステート5020に飛ぶ処理がなかったのを修正
・ダウン時かつpos yが0のとき、攻撃を受けた瞬間にliedown recovertimeが1減る処理が無かったのを修正
・ダウン時かつpos yが0のとき、攻撃を受けた瞬間gethitvar(yvel)が0以外だとpos yが15増加する処理がなかったのを修正
・fall.yvelocityが0になる条件にpos yとgethitvar(yvel)の指定が無かったのを修正
・fallcountが1から増加する度にliedown recovertimeが半減する処理が無かったのを修正
・ボタン押しによるliedown recovertime短縮条件がfallcountが1以上の場合になるよう修正
・ダウン時に自動的に無敵時間が入る処理が無かったのを修正
　無敵処理の条件は"fallcountが3以上"もしくは"liedown recovertimeが0"になってからステート5100に入ること
（MUGENではより緩い条件になっているが、詳細が不明なため暫定）
・movedYフラグは必要ないことがわかったため削除
=> ダウン時のハードコード処理でMUGENと異なる動作の修正

README.md, src/bytecode.go, src/char.go, src/lifebar.go, src/script.go
・explodのspaceとpostypeを同時に設定した場合の優先度を修正
・nofallcount時にもボタン押しでrecoverTimeが減少するように修正
=> explodのspaceとpostypeを同時に設定した場合の優先度を修正

external/script/storyboard.lua
What do you think about this feature? It allows creating scrolltexts in storyboards by simply adding a velocity value (`layerXX.vel`).
Here is a sample storyboard ([credits.def.txt](https://github.com/ikemen-engine/Ikemen-GO/files/8798582/credits.def.txt)) and a video showing it in action:
https://user-images.githubusercontent.com/245089/170999539-10ed1b57-c544-45ac-abd1-c18fc6f7ddc8.mp4
=> Feature proposal: text layer velocity

src/bytecode.go, src/char.go, src/stage.go
・StageInfoのxscaleとyscale設定時hiresフラグによる倍率変更が無効化される処理が無かったのを修正
・Helperのownpalが省略時1になっていたのを修正
・Hitpause中にChangestateした際にHitpause終了までpersistentがリセットされない不具合を修正
=> StageInfoのxscaleとyscale設定時hiresフラグによる倍率変更が無効化される処理が無かったのを修正

src/bytecode.go, src/char.go
・stateno=20の時ctrlが無いとstateno=0に戻らない場合があったのを修正。
・TargetBindをしたHelperがDestroyselfをすると5050へ送られる処理がMovetpe=Hの時のみになるように修正。
・TargetBindと同時にDestroyselfをすると5050へ送られる処理が無効になるように修正。
=> ・stateno=20の時ctrlが無いとstateno=0に戻らない場合があったのを修正。

external/script/main.lua, external/script/motif.lua, external/script/start.lua
=> Character select Skip Slot added

src/char.go
・Targetbind時の速度が拘束後も継続する場合があったのを修正。
=> ・Targetbind時の速度が拘束後も継続する場合があったのを修正。

src/bytecode.go, src/char.go, src/render.go
・ExplodのPostype=N時にデフォルトのbindtimeが0になっていたのを修正
・HitdefのGuard.Distが機能していなかったのを修正
・ModifyExplodでbindtimeを変更すると座標が初期化される場合があったのを修正
・aglOverフラグは必要なくなったため削除
=> ・ExplodのPostype=N時にデフォルトのbindtimeが0になっていたのを修正

src/bytecode.go, src/char.go, src/system.go
・KO判定が出るタイミングが1F遅くなる場合があったのを修正
・ScreenheightとScreenwidthがMUGENと微妙に誤差が出ていたのを修正
・projremove時の向きとremvelocityがMUGENと異なっていたのを修正
・enemyExplodsRemoveをコメントアウト
=> ・KO判定が出るタイミングが1F遅くなる場合があったのを修正

external/script/main.lua, external/script/start.lua
=> Fixed: Cell skip bug [#571]

src/char.go
・Hitdefのground.type=None時にヒットポーズが発生していたのを修正
・clns1の赤枠が重なるとclns2が無くても押し出し判定が出現する不具合を修正
・被撃時に所持ターゲットが外れる仕様が無かったのを修正
・その際にtargetbindしていると対象が5050に飛ぶ仕様が無かったのを修正
・Explodのpausemovetimeとsupermovetimeで動ける時間が1F短かったのを修正
=> ・Hitdefのground.type=None時にヒットポーズが発生していたのを修正

src/bytecode.go, src/char.go, src/sound.go
・sndでサイズが小さすぎるwavを読み込まないようにした
・Projectileのpausemovetimeとsupermovetimeで動ける時間も1F短かったのを修正
・Invisible中に残像が出なくなっていたのを出るように修正
・ProjMissTime省略時の挙動が異なっていたのを修正
=> ・sndでサイズが小さすぎるwavを読み込まないようにした

src/camera.go, src/stage.go
・tensionhighをtensionlowと同時に記述しないと機能しないようにした。
・boundlow関連を調整
=> ・tensionhighをtensionlowと同時に記述しないと機能しないようにした。

src/bytecode.go, src/char.go, src/compiler_functions.go
Add second parameter in hitdef redlife.
=> Guard redlife in hitdef

src/char.go
・nochainidが設定されているとchainidが無視されるように修正
・projectileではchainid、nochainidが無視されるように修正(ikemenversionの設定で解除可能)
=> ・nochainidが設定されているとchainidが無視されるように修正

src/char.go
This fixes a problem with kfm not being able to perform its `TargetBind` based throw. Also, char width/edge is now reset before `posUpdate()` is called, fixing misplacement issues when `width` SCTRL is followed by a sudden change to a state that limits char movement (best exemplifed by MKP's Bell Tower stage fatality)
=> Fix char bind, fix char misplacing when using width

src/compiler.go, src/system.go
・statedefのステートナンバーに特定の記号が含まれていると認識しない場合があったのを修正
・振り向きAnim再生中にラウンド終了時ステートに移動した時、そのステートにAnimがない場合振り向き続ける現象を修正
=> statedefのステートナンバーに特定の記号が含まれていると認識しない場合があったのを修正

src/char.go
・Roundstateが3の時にctrl関係なく振り向く処理がなかったのを修正
=> ・Roundstateが3の時にctrl関係なく振り向く処理がなかったのを修正

src/render.go, src/render_gl.go, src/system_glfw.go
When using GLFW, the swap interval must be set when the GL context is active.
=> Fix GL initialisation

src/bytecode.go, src/char.go, src/compiler_functions.go, src/script.go, src/sound.go
This commit adds a new PlaySnd parameter priority.
```
priority = pri (integer)
Does nothing when channel is not specified
Set the priority of the sound
A sound with higher priority will not be interrupted by sounds with lower priority
Default value is 0
```
=> New PlaySnd Parameter: priority

go.mod, go.sum
=> Update glfont dependency to fix alignment issues in TTF rendering

src/compiler_functions.go, src/image.go, src/stage.go, src/system.go
・BGpalfxがポーズ中に停止しないように修正
・BGpalfxが1F遅れていたのを修正
・helperのsize.proj.doscaleがintで読み込まれてなかったのを修正
=> ・BGpalfxがポーズ中に停止しないように修正

src/bytecode.go, src/char.go
・localsclの計算時に誤差が出にくくなるように修正
・Fall.Envshake.Amplをlocalcoordの違いで変動しないように修正
=> localsclの計算時に誤差が出にくくなるように修正

src/image.go
=> スローダウン時にBGpalfxが切れてたのを修正

external/script/motif.lua, src/bytecode.go, src/char.go, src/common.go, src/compiler_functions.go, src/script.go, src/stage.go
Issues #431 and #694 are addressed in this PR.
=> Bugfixes and new parameter for ChangeAnim (ReadPlayerID)

src/char.go
#725 is fixed with this commit, along with some other things related to pos updating and trigger/SCTRL redirection.
=> Fix BackEdgeDist, PosFreeze and NoGetUpFromLieDown redirection

src/bytecode.go, src/char.go
・起き上がりステートのtimeが不正確になっていたのを修正
・GameHeightとGameWidthの処理がステート奪取側基準になっていなかったのを修正 #566
=> 起き上がりステートのtimeが不正確になっていたのを修正

src/compiler.go
```coffescript
ignorehitpause if playerno = 2 {
if time > -1 {
text{
text: "This is a text";
pos: 100,100
}
}
}
```
Running the code above, text will fail to draw during a hit pause due to 'if time > -1' subblock not inheriting the 'ignorehitpause' attribute from the main block in the compiler. This commit attempts to fix that assuming this behavior makes more sense.
=> Make ignorehitpause block affect its nested blocks in ZSS

src/char.go
投げ属性ヒット時のフレームは他の攻撃が当たらなくなるように修正 
#607
=> 投げ属性ヒット時のフレームは他の攻撃が当たらなくなるように修正

data/common.cmd, src/char.go
・Reversalにattrを設定すると効かなくなる不具合を修正#744
・common.cmdがcommand.buffer.timeの影響を受けないように修正
=> Reversalにattrを設定すると効かなくなる不具合を修正

src/bytecode.go, src/char.go, src/compiler.go, src/compiler_functions.go, src/script.go, src/sound.go, src/system.go
Also, PrevAnimNo was renamed to PrevAnim for consistency. #518 is partially handled in this PR (the BGM part).
=> New utilities for BGM manipulation, fixes

data/guardbreak.zss
Mostly about the suggestions mentioned in #756
=> Guard break system update

src/char.go
affectteam = FのHitdefがreversaldefに当たらないのを修正
=> affectteam = FのHitdefがreversaldefに当たらないのを修正

src/bytecode.go, src/compiler.go
Needed for 66b82d07f07ab8ca85c445be827b4348bf6afd26
=> Add player() trigger redirection

src/camera.go, src/system.go
・boundhighがzoomoutの値によって変動するようにした #588
・ズームアウト時にtensionhighの始点が変化しなかったのを修正
・tensionlowに暫定対応
=> boundhighがzoomoutの値によって変動するようにした

src/camera.go, src/stage.go
・Boundhighが0以上になったときの処理を追加 #239
・tensionhighがzoffsetで変動していたのを修正
・ズームアウト設定かつ非ズームアウト時にステージ上限に行くとレイヤーがdelta値を無視する場合があったのを修正
=> Boundhighが0以上になったときの処理を追加

src/bytecode.go, src/char.go, src/compiler.go
Issues #705, #786 and #787 are addressed in this PR.
=> Bugfixes and new trigger: selfcommand

src/char.go
・Gethitvar(isbound)が不自然に維持される現象を修正#780
・bind中にDestroyselfをすると5050に飛ぶ処理が発生しない不具合が再発していたのを修正#194
=> Gethitvar(isbound)が不自然に維持される現象を修正

src/bytecode.go, src/char.go
VelSetに問題があったため一部の処理を戻し、bind中のposトリガーが1F遅れる問題の応急処置を入れた
=> VelSetに問題があったため一部の処理を戻し、bind中のposトリガーが1F遅れる問題の応急処置を入れた

src/char.go
・p2stateno時のprevstatenoをstatetype別に設定されるように修正#765
・Helper生成時のフレームで防御力が0になっていたのを修正
=> p2stateno時のprevstatenoをstatetype別に設定されるように修正

src/char.go, src/compiler.go, src/script.go
・P2リダイレクトの処理を整備して、敵と敵の間のちょうど真ん中に立つと振り向き続ける現象を修正 #606
・P2をcns/zssでもリダイレクトとして使えるようにした
=> P2リダイレクトの処理を整備して、敵と敵の間のちょうど真ん中に立つと振り向き続ける現象を修正

src/bytecode.go, src/compiler_functions.go, src/system.go
・Zoom時にカメラによる画面端を考慮した処理が無かったのを修正 #803
・Zoomステコンにtimeを追加
=> Zoom時にカメラによる画面端を考慮した処理が無かったのを修正

src/render_gl.go, src/render_kinc.go, src/system.go
This patch moves the logic introduced in bab71bc218f34fffb44969efacb7b2b5b1bd872c to places that do not depend on the platform.
=> Fix flickering with netinput and the Kinc backend

src/char.go
・Projectile生成時に使い終わった既存IDを上書きする時に、そのフレーム中は一度確認したIDを再確認しないようにした  #366
・Projectileのhitonceが0でも一度に複数の相手に当たらない状態になっていたのを修正
・attrにP属性が入っているProjectileは1Fに一つしかヒットしない仕様が無かったのを修正
=> Projectile生成時に使い終わった既存IDを上書きする時に、そのフレーム中は一度確認したIDを再確認しないようにした

src/script.go
ズーム時のY軸変動が戦闘画面以外に残っていたのを修正 #958
=> ズーム時のY軸変動が戦闘画面以外に残っていたのを修正

src/bytecode.go, src/input.go
gametimeがオンライン対戦とリプレイで非同期を起こしていたのを修正
=> gametimeがオンライン対戦とリプレイで非同期を起こしていたのを修正

data/action.zss
Fixed a typo that made the message pop up more frequently than intended for CPU players.
=> other: Fixed typo in Just Defended

src/bytecode.go, src/char.go, src/compiler.go, src/compiler_functions.go, src/script.go, src/stage.go
=> feat: new EnvShake sctrl mul parameter, HitDef envshake.mul, fall.envshake.mul, gethitvat(fall.envshake.mul)

src/bytecode.go, src/camera.go, src/char.go, src/compiler.go, src/compiler_functions.go, src/stage.go
Each feature has its explanation in the commit messages. New features:
- **Stage [Camera] ZoomAnchor parameter**: changes zoom out behavior to match 0.98.2
- **Stage [Camera] TensionVel parameter**: multiplies tension correction velocity in horizontal camera tracking
- **Camera SCTRL**: New controller that adds new ways to control the in-game camera.
=> feat(camera): ZoomAnchor, TensionVel, Camera SCTRL

data/action.zss, data/dizzy.zss, data/functions.zss, data/score.zss, data/tag.zss, data/training.zss, src/resources/defaultConfig.json
action.zss and score.zss refactored to call functions from a new functions.zss.
=> refactor: add functions.zss

src/lifebar.go
=> fix: text sctrl flicker

src/bytecode.go
=> fix: offset+redirectId not accounting for localcoord

src/bytecode.go, src/char.go
standby、destroyself時に相手のp2情報から消去されるように修正
Fixes #1109
=> fix: p2 data cleared during standby, destroyself

src/bytecode.go
=> fix: modifyExplod remapPal

src/char.go
Addresses #713 and a slight regression in #1072 that made gethitvar(hittime) start decreasing one frame later.
Fixes #713
=> fix: Hittime frame of delay and dust generation

external/script/global.lua
=> fix: fixed debug animation data looking one frame ahead

data/system.base.def, src/bytecode.go
=> fix: gameMakeAnim under parameter

src/char.go
=> fix: projectile triggers readable by helpers, without redirecting to root

data/tag.zss
StateDef -3 => StateDef -4
changeState -> selftState
=> fix: better compatibility for tag customstated chars

data/tag.zss
- Replaced the landing triggers with the same ones found in the common1 states
- Fixes #1019
=> fix: some characters not landing after tagging in

src/char.go
- Fixed the Projectile EdgeBound parameter. It now uses the edges of the screen as reference instead of the actual playable area (fixes #1100)
- Fixed Back AnimType not triggering when a character is on the ground
=> fix: projectile edgebound, animtype setting

src/script.go, src/sound.go
=> fix: bgmLength/bgmPosition not resetting

src/char.go, src/compiler.go, src/compiler_functions.go, src/script.go, src/system.go
- Prevents a player from being forced to the starting position after the intro (#1161)
- Fixed #1148
=> feat: new AssertSpecial flag - nointroreset

src/char.go, src/sound.go
- Fixed ReversalDef not attributing GetHitVars for ID or PlayerNo to the target
- Fixed typo in PlaySnd priority function
=> fix: reversaldef and gethitvar(id)

src/system.go
- Adjusted RoundNotOver AssertSpecial so that it only freezes the win pose timer at the specific time where it is necessary
- Minor adjustments to make round end timing more like Mugen
- Fixes #1000
=> fix: RoundNotOver flag behavior

src/char.go, src/compiler.go
=> fix: newline problem with common.air and common.cmd

src/bytecode.go
=> fix: sound spam during victory screen

src/char.go
- Fixed regression that made characters unable to guard while under the effect of the opponent's pause
=> fix: unable to guard while paused

data/training.zss, external/script/global.lua, src/input.go
- Debug keys are now allowed while the game is paused
- Pressing Pause with the Menu open closes it (fixes #1008)
- Setting the training dummy to jumping no longer prevents them from recovering sustained damage
=> other: debug keys allowed while paused

src/char.go, src/lifebar.go, src/system.go
This is a continuation #1214, where various timing and ctrl handling discrepancies at round end phase are addressed.
Fixes #1193
=> fix: Round end timing discrepancies

src/system.go
- Reverted some prior changes to the fadeout effect's timing
- Fixes #1238 (which is a bug report rather than a discussion)
=> fix: fadeout times on round end

src/bytecode.go, src/char.go, src/compiler.go, src/script.go
Redirrect trigger which returns helper entity by index.
=> feat: Helperindex redirrect trigger

src/bytecode.go, src/common.go, src/compiler_functions.go, src/image.go, src/script.go, src/stage.go
SinMul SinColor parameters for all palfx functions. 
sinmul = ampl_r, ampl_g, ampl_b, period (int, int, int, int)
sincolor = ampl, period (int, int)
=> feat: palFX SinMul SinColor parameters

src/camera.go, src/stage.go
partially revert the changes that were causing the issue with #1334 in #1323
the problem in #1319 is still fixed
=> fix: regression in zoom camera

data/training.zss
- The training dummy's life is no longer reset while it is dizzy
=> fix: training dummy life recovery while dizzy

src/anim.go, src/bgdef.go, src/char.go, src/common.go, src/image.go, src/lifebar.go, src/script.go, src/stage.go, src/system.go
Implement SFF caching again #770
and changed to load char palettes separately for each char instead of for each SFF #822
=> feat: Implement SFF caching again

src/char.go, src/sound.go
Channel = -1 sounds are not interrupted by play/stopSnd with channel >= 0.
Fixes #1190
=> fix: make sound channel work more like MUGEN

src/bytecode.go, src/char.go
The fix in #501 is broken by #1192
This commit fixes it.
=> other:Fix Offset Problem

src/sound.go
Fix the bug where the correct sound channel is not stopped.
Fix #1425
=> fix: Fix StopSnd bug

src/anim.go
- Reflection intensity was incorrectly being affected by shadow intensity
- Fixes #1354
=> fix: Trans effect on reflection intensity

src/lifebar.go
This PR adds multiple bg0 elements to `[Powerbar]` similar to multiple front elements (`p<n>.front<value>`.)
It also moves relevant reading code to separate functions (`readMultipleValues`, `readMultipleValuesF`.)
=> feat: powerbar multiple bg0 elements

src/render.go, src/shaders/sprite.frag.glsl
this PR fixes stages bgdef mask param of rgba sprites #1468
=> fix: Stages bgdef mask param rgba sprites fix
