build.sh, build_all.sh, docker_build.sh, get.sh
Added changes to build.sh and get.sh scripts to allow setting cross-compiling environment variables.
This variables are used by the docker-image ikemen-dev that set the compilers and build the binary for the respective target.
Look at the docker-build.sh file to see examples on how to use the image.
=> Added support for cross-compiling Ikemen-go-plus using Docker

external/script/start.lua
there should be no difference between cursor staying in the same position and moving - in both cases all slots are rendered. So yeah, something silly like this had to be responsible for the massive performance hit observed on larger rosters.
=> fixed massive lag when moving from cell to cell

Make.linux, Make.macos, Make.ubuntu, Make.windows, Makefile
This patch adds a Makefile for building the executable files and zip files.
Invocation looks like this:
`CONF=linux make pkg`
Or on Ubuntu (to add the al_cmpt tag):
`CONF=ubuntu make pkg`
This produces nearly-identical zip files to release 0.97.0, with the following differences:
* All files are within a top directory.
* The save directory is not included.
Building individual files is easy. Just specify the filename.
`CONF=ubuntu make Ikemen_GO.exe`
`CONF=ubuntu make Ikemen_GO_CoreOnly.zip`
This can be used to separate build steps in the CI script, as you seem to prefer.
This obsoletes the following files, which can be removed once the CI is changed to use the Makefile.
* build/build.sh
* build/build.cmd
* build/pack_release.sh
* build/get.cmd
* build/get.sh
* build/docker_build.sh
* move …
=> add Makefile

src/bytecode.go
Workaround for the crash when entering a match on an arm32 device. (rPi). This was caused by a byte misalignment on be[i+1]. This is resolved by recreating the float in byte aligned memory and pushing that float to the stack.
=> Workaround for byte misalignment on arm32 (rPi)

src/render.go
Modifed the texture mapping constant in the fragment shader very slightly to re-align the palette textures for the rPi 4.
=> Fixed Texture Mapping Issue on the rPi

src/script.go
This PR adds a `screenshot()` function to IKEMEN's LUA functions, to allow for the ability for scripts to take screenshots without the user having to manually press F12.  It does this by invoking the already-existing `captureScreen()` function on the Go side of things.
This is useful for automation, e.g. loading a stage, taking a screenshot of the stage, and then closing the game.
=> Add "screenshot()" function to LUA

src/bytecode.go, src/char.go, src/compiler_functions.go
#407 
This PR adds palfx parameters to Explod/ModifyExplod similar to the parameters in hitdef. It works for both character's anim and fightfx's anim. The ownpal of the explod need to be set to 1 when using the palfx parameters.
Example code using the parameters.
```
Explod{
anim:6000;
Id:6000;
pos:0,0;
bindid:id;
bindtime:-1;
facing:facing;
sprpriority:3;
ownpal:1;
ignorehitpause:0;
palfx.time:10;
palfx.mul:256,256,0;
}
```
It is useful for creating color changing explods, especially when the explods need to have ignorehitpause = 0.
=> Add palfx parameters to Explod/ModifyExplod

src/render.go
This commit changed the shader and the rendering function to fix the problem where the image color is multiplied by the image alpha twice.
=> fix Explod transparency bug

src/input.go
Setting `sys.keyState[glfw.KeyUnknown]` to `true` can have undesired side effects. For instance, if a joystick button is unmapped (mapped to -1) and multimedia keys are used to change the system volume, `JoystickState()` may return `true`, triggering an event for a button that was explicitly disabled in the config.
=> Do not register keyboard state for glfw.KeyUnknown

src/anim.go, src/bytecode.go, src/char.go, src/common.go, src/compiler.go, src/compiler_functions.go, src/font.go, src/image.go, src/render.go, src/stage.go, src/system.go
This commit adds two parameters to explod and modifyexplod
```
projection = type_string (string)
Does nothing when xy angles are 0
orthographic: the default value when mugen version is not 1.1 or ikemen version is not 0
perspective: the default value when mugen version is 1.1 and ikemen version is 0, distortion is affected by the position of the sprite relative to the center of the screen.
perspective2: distortion is affected by the position of the sprite relative to the center of the animation.
focallength = focal_length (float)
Focal Length of the projection. Does nothing when projection type is not perspective. Scales internally like xy scales so that the explods looks the same under different resolution/loaclcoord/camera zoom values.
Default value is 2048
```
=> Add perspective projection

src/render.go
Similar to #416. 
This commit fix the transparency of RGBA images when trans = AS256D256
=> Fix trans add bug

src/font.go
This is a more efficient way to print strings that may contain `%`.
=> Avoid a string replace call in the text printing code

src/anim.go, src/image.go
Hi. This is a reworked version of #441, split into three commits, with the regression fixed, as well as another overlook of my part (`shareCopy()` needs to propagate `coldepth` instead of `rle`).
=> Support non-RLE SFF contents

src/camera.go
Vertical bounds need to be computed even when verticalfollow is 0, because they
are needed to apply the zoom level. Without this fix, one would need to set
verticalfollow to e.g. 0.0001 in order for zoomout to have any effect.
=> Fix stage zoom behaviour when verticalfollow is 0

build/build.sh
The OS X version of bash does not understand ${,,} syntax, so use the "case" idiom
instead. Also do not try to use o64-clang when not cross-compiling.
=> Fix Mac OS X native build

external/script/motif.lua
This change increases motif/screenpack portability by letting the external module file defined in _[Files]_ section at _system.def_ to be detected inside the motif subdirectory (or data folder). Without this, the full path to the module has to be declared for it to work.
=> Add general paths search support to system.def file 'Module'

Makefile, src/main.go, src/system.go, src/util_desktop.go, src/util_js.go
This makes it possible to not use the Sqweek library when targeting JavaScript
or Wasm. These changes are necessary for #485.
=> Move message box functions to separate files.

src/bytecode.go, src/char.go
This commit fixes a bug where the offset value set by the offset controller is scaled incorrectly when 
-  the characters are in different localcoord
- p2 is in p1's state and non zero offset is set by the offset controller.
- p2 get back to it's state by selfstate or getting hit by p1 -> p2's localscl is changed and the offset value is scaled incorrectly.
=> fix offset controller bug

src/sound.go
This issue was introduced when porting Ikemen to Ikemen Go. The original code can be
seen here: https://github.com/Midiman/ikemen/blob/master/src/alpha/sdlplugin/sdlplugin/sdlplugin.cpp#L811
=> Fix a regression in the audio normalizer

src/font.go, src/util_desktop.go, src/util_js.go
This allows to disable TTF loading when targeting JavaScript, which does not have the findfont or glfont libraries.
=> Move core TTF loading code to a platform-specific file

src/bytecode.go, src/char.go, src/script.go
・永続ターゲット(Reversaldef marking)がMUGENと同様に機能するように修正
・Const(Data.Fall.Defence_Mul)トリガーの数値が反転していたのを修正
=> ・永続ターゲット(Reversaldef marking)がMUGENと同様に機能するように修正

src/stage.go
Due to a bug, whenever a window moves off-screen, at least in the x-direction and to the left, if it moves far enough off-screen, the bounding box goes haywire, where it will now assume the maximum size (width).
Before:
After:
This fix was made after trying to figuring out what went wrong with one of my stages, [Butter Building](https://area91.garycxjk.com/mugen/stages/nintendo/kirby/kabutterbuilding). As a side note, only the non-zoom version works properly, due to sprite positions not being rounded down to the pixel. The main issues were with the Shotzo (the cannons). To give them the illusion that they turn with the tower, I used `window` / `maskwindow` which have a very high delta, so that they'd immediately hide the Shotzo sprites whenever they should be invisible.
=> Background sprite hiding when window off-screen

src/char.go, src/system.go
・攻撃判定の処理時にHitdefattrを持つキャラの優先度が高くなるようにした。
・Reversaldefでp2statenoを指定するとターゲットが取れない場合があったのを修正
=> ・攻撃判定の処理時にHitdefattrを持つキャラの優先度が高くなるようにした。

src/render.go
Using medium precision was enough in most situations, but causes rendering artifacts in animated stages that use the fullscreen billboard technique, such as Endless Stairs Stage.
=> Increase floating point precision in sprite rendering shaders

src/anim.go, src/compiler_functions.go, src/shaders/sprite.fs.glsl, src/stage.go
・ステージのtileのxでマイナス値が指定された時の挙動が異なっていたのを修正
・Trans=sub時にマスク部分の透明度が逆転する場合があったのを修正
・ForceFeedbackのwaveformを"で括っていても読み込むようにした（書き間違えてるキャラが無視できないほど多いため）
・AIRのtimeが-1に指定されてる場合でもInterpolate系統が適応されていたのを修正
=> ・ステージのtileのxでマイナス値が指定された時の挙動が異なっていたのを修正

src/camera.go, src/stage.go, src/system.go
・zoomout時にY軸の地面側にスクロールが入る1.1の仕様を実装
・zoomoutによるステージ端の変動処理が縦横比変更に対応できていなかったのを修正
・boundlowが0以外だとズームアウト時に背景が少しズレるのを修正
・cutlowで反映される値に制限がなかったのを修正
・画面外を黒く塗りつぶす処理をコメントアウト
=> ・zoomout時にY軸の地面側にスクロールが入る1.1の仕様を実装

src/camera.go, src/char.go, src/system.go
In mugen, the camera always follows the highest player available in the Y-axis, and, when there are no characters left to track (meaning all chars have movecamera Y set to 0), the camera rests wherever it has landed until there's a new character to track. This change deprecates use of "lowest", since it serves no purpose for camera tracking other than setting the lowest value possible to highest before finding the real highest value. I also simplified some math operations.
=> Fix camera follow priority

src/camera.go, src/char.go, src/system.go
As discussed in #620, this PR attempts to address a problem introduced in commit 51e3e24ddd4acad749a8f30e373fcede80a90daa and partly fixed by 70a87c95c960a4d9186b4a1c28a59af9014e49d1. Seeing "lowest" is necessary for tensionhigh and tensionlow to work properly (which former commit wasn't taking in account), it was needed to be reintroduced, but the priority problem was still present when not using tensionhigh/tensionlow. With these changes, camera should work properly for both modes.
Also, `c.boundLo` now has its value correctly set.
=> Tweaks to lowestを巻き戻し

src/bytecode.go, src/char.go
・explodのsuperpausetimeとpausemovetimeが最大値を超えるとオーバーフローしていたのを修正
・explodとprojectileのsuperpausetimeとpausemovetimeがマイナスに入力されていた場合の動作を修正
=> ・explodのsuperpausetimeとpausemovetimeが最大値を超えるとオーバーフローしていたのを修正

src/script.go
Joystick configuration is done by observing transitions from "some button is pressed" to "all buttons are released" state. See function "f_keyCfg" in "external/script/options.lua": https://github.com/ikemen-engine/Ikemen-GO/blob/0.98.2/external/script/options.lua#L1754-L1761
But right now "getJoystickKey" function returns "-11" for an idle PS3 controller with no buttons pressed (because axes 2 and
5 have -1.0 value in this state). The game does not see the "all buttons are released" state and this breaks the joystick configuration process.
This patch fixes the problem by just skipping axes 2 and 5. So that the "getJoystickKey" function returns "" in an idle state
as expected.
Only tested in Linux. I'm not sure what is the PS3 controller support status in Windows.
=> Fix PS3 controller detection

src/anim.go, src/bytecode.go, src/char.go, src/compiler_functions.go, src/system.go
This commit adds a new Explod parameter clipwindow. 
```
clipwindow = x1, y1, x2, y2 (float)
This parameter takes four numbers in the format of clsn which forms a rectangle 
where pixels beyond the rectangle are not rendered. 
```
This makes things a lot easier when making gauges and animations like the gif below.
=> Add Explod clip window

data/common.cmd, src/anim.go, src/bytecode.go, src/camera.go, src/char.go, src/compiler.go, src/compiler_functions.go, src/script.go, src/stage.go, src/system.go
Details of all changes can be read on the commit themselves, but, to summarize the changes:
- Inline map assignation (`map(something) := 10`) is now possible in ZSS, and in MapSet SCTRLs in CNS.
- All [Files] parameters in chars are now optional, improving AttachedChar portability a lot.
- A missing feature from mugen 1.1 was added: Stage [Shadow] xshear.
- Code related to camera and stage was modified to create a better base for a new SCTRL. Also, bug related to camera tracking and frame rendering when playing with an odd GameFramerate/GameSpeed value was fixed. To reproduce the bug in Ikemen GO 0.98.2, set GameFramerate to an odd number like 55 or 26, then, in a stage with a high boundhigh value and a verticalfollow of 1,  try to add Y Vel to a character. You'll see the character starts …
=> New features: Map assignation, Stage shadow xshear (missing mugen feature), ModifyStageVar SCTRL

src/bytecode.go, src/char.go, src/compiler_functions.go, src/stage.go, src/system.go
First fix is self-explanatory, when modifying StageVars via ModifyStageVar and then pressing F4 to reset the round, modifications persist, so this was fixed. StageVars now get reset on F4 based on the values they had when starting the round.
Map assign in CNS (inside MapSet SCTRL) now can be done via '=' or ':=', like VarSet SCTRL. This only affects the MapSet-related SCTRLs, map assignments done inside a statement only work with ':=' operator.
Latest thing is a major change in chars' `action()` code processing order. The code was divided in three phases: `actionPrepare()`, `actionRunStates()` `actionFinish()`. The idea is then to establish a new base for char action performing in a way that addresses problems like Assert SCTRLs not being able to be redirected (#540), and possible char …
=> Fix StageVars modified not getting reset on F4, changes in chars' action() code

src/bytecode.go, src/stage.go
In mugen 1.1, envshake has a stronger movement effect than in Ikemen GO. This problem is best exemplifed by Mortal Kombat Project's Bell Tower stage. This stage has a special stage fatality that makes high use of envshake SCTRL to control the camera (probably to compensate for mugen limitations). Without these changes, camera will fail to follow the player.
Test case: https://files.catbox.moe/u1sbc0.7z
How to test the stage:
- Go to round 2
- Press shift + F2 to set p2 life to 1
- Perform an uppercut on p2 to activate the stage fatality
=> Fix envshake intensity

src/script.go
This patch protects the Go runtime against invalid arguments from the Lua side.
=> Prevent potential crashes in getJoystickPresent() and getJoystickKey()

src/system.go
As reported in the [discord server](https://discord.com/channels/233345562261323776/233363722934943744/1011062604493508648), collisions were getting "offseted". Collision debug draw positions are determined inside `cueDraw()` function based on camera pos values. Camera was getting updated after clsn pos was determined, so this meant clsn boxes weren't being showed in their real positions. Camera update code had to be re-placed before cueDraw() execution to fix this. Also, according to the user who reported this bug, actual collisions (not just the debug drawings) were also getting badly positioned, though I haven't found any indications of this in my tests. In any case, the user reported that it was also fixed by this.
Second fix, asserting `roundnotskip` flag at all times inside states …
=> Fix collisions, fix roundnotskip not working at the start of state 170/175/180

src/camera.go, src/stage.go
boundlow設定時に実際の地面の高さがfloortensionとverticalfollowの影響を受ける仕様が無かったのを修正。
=> boundlow設定時に実際の地面の高さがfloortensionとverticalfollowの影響を受ける仕様が無かったのを修正。

src/sound.go, src/stage.go, src/system.go
When bgmloopstart is specified in a stage, music should always loop starting from that point. A custom streamer was made as to handle loop points with greater precision, and now loop points are taken into account when loading stages from command line.
=> Fix loop points behavior and improve loop accuracy

src/render.go, src/render_gl.go
This continues the work of removing all OpenGL-specific function calls from `render.go` and move them into `render_gl.go`.
=> More refactoring in render.go

src/bytecode.go, src/compiler_functions.go, src/stage.go
- **RemapPal**: Remaps a palette from stage sff file to another palette from the same file. This can be used to perform static palette changes without having to duplicate sprites.
- **PalFX**: Applies palette effects to individual background elements. It works in a different layer than BGPalFX, meaning BGPalFX will be applied over BG elems' PalFX instead of substituting them. Due to the nature of BGCtrls, PalFX is permanently applied to its BG element the moment `time` triggers it (though it can be overriden by a new PalFX definition).
In both cases, BGCtrls can be modified via ModifyBGCtrl SCTRL.
=> New BGCtrls: RemapPal, PalFX

src/image.go, src/input_kinc.go, src/render.go, src/render_gl.go, src/render_kinc.go, src/system_kinc.go
The Kinc library (https://github.com/Kode/Kinc) is a cross-platform low-level library that helps port games to multiple platforms, including consoles such as the Switch, the PlayStation or the Xbox Series. This branch is still a work in progress, and it will require a lot of documentation, but I have already successfully run an Ikemen-based game on these platforms using the Kinc backend.
The OpenGL/GLFW backend stays as is and is not affected by these patches.
=> Add a rendering backend and an input layer for the Kinc library

src/input.go, src/input_glfw.go, src/input_kinc.go, src/script.go, src/system.go, src/system_glfw.go, src/system_kinc.go
This PR implements keyboard input for the Kinc backend.
This also means that GLFW is no longer used outside of the specific `_glfw.go` files, so it should be now possible to implement other backends (SDL maybe?).
=> Keyboard input for the Kinc library

src/bytecode.go, src/char.go, src/stage.go
Quick set of various bugfixes I've been collecting the last month (or so). I focused all of my energies into finding a proper solution for correct synthesizing of BGPalFX into PalFX from BG elements... without good results, so I went for an alternative that works well for now.
Also, I tried to deal with #658 based on observations from my part. The problem might or might not be fully solved, it will depend on further tests, but I can confirm some of the symptoms were lifted.
=> Various bugfixes: Fightfx scale, PalFX BGCtrl and BGPalFX, Game crashes

src/char.go
AttachedCharをデフォルトではstandby状態になるように変更
#637
With this change, AttachedChars must be "Tagin" if they are going directly into fight.
=> AttachedCharをデフォルトではstandby状態になるように変更

src/char.go
This commit fixes the problem where something like this works in mugen but not in ikemen.
```
[Statedef 200]
...
[State 0, ReversalDef]
type = ReversalDef
trigger1 = 1
reversal.attr = SCA,AA,AP;
attr=SCA,AA,AP;
hitflag=MAFDP;
numhits=0;
pausetime=0,0
p1stateNo=201
sparkno = -1
hitsound = -1
...
[StateDef 201]
...
[State 0, TargetState]
type = TargetState
trigger1 = numtarget
trigger1 = !time
value = 202
ignorehitpause = 1
```
This should fix #388 as well.
=> Fix reversaldef target problem

src/bytecode.go, src/char.go
・freqmulの値に制限をかけるように修正
・Reversaldef不成立時に相手の攻撃判定と自分の攻撃判定と当たり判定が重なっている場合に攻撃がすり抜ける現象を修正
=> freqmulの値に制限をかけるように修正

src/char.go
This commit fixes the screen bound calculation when width is set.
=> Fix width bug

src/char.go
Targetbind後に同じキャラが攻撃を当てるとbindが外れる仕様がなかったのを修正
#730
=> Targetbind後に同じキャラが攻撃を当てるとbindが外れる仕様がなかったのを修正

src/char.go
This commit fixes the bugged collision calculation happened when a hitdef with p2stateno contacts.
=> Fix collision calculation

external/script/main.lua
Fixes #722 .
Instead of using the #main.t_selChars to check which character slot we are at, it now manually increases the value. It was previously assumed that slotted characters wouldn't count towards the total, which was a wrong assumption.
=> Fixed: Skip doesn't work properly with slots

external/script/global.lua, src/char.go, src/compiler.go
For ChangeAnim's ReadPlayerID bug, when a character got into another player's animation, but that player sff was V1, animations were getting wrong palette colors due to improper palette handling after anim change. A basic fix was included that seems to work fine, but might change in the future depending on how this new parameter will evolve.
Giving more process priority to characters with Idle movetype fixes a problem where they can't get GetHitVar values from a character in GetHit movetype. Chars in Attack movetype still get the highest priority, following previous Ikemen GO behavior.
=> Bugfixes: challenger mode, char processing priority, ChangeAnim's ReadPlayerID palette bug

src/bytecode.go, src/char.go, src/compiler.go
This commit adds a new trigger `reversalattr` which is similar to `hitdefattr`. It checks the attribute parameter of the player's currently-active ReversalDef.
=> New trigger reversalattr

src/bytecode.go, src/char.go, src/compiler.go
Doesn't make sense to approve/reject a perfectly valid expression depending on the mugenversion of the character.
I also added a new trigger that I think could be useful, by a suggestion of an user. 👀
=> Make != operator work with hitdefattr in all mugenversions

src/compiler.go
For example, having this code:
```coffeescript
if movetype = A {
ignorehitpause if 1 {
text{
text: "Foo";
pos: 100,100;
}
}
if 1 {
text{
text: "Bar";
pos: 100,200;
}
}
}
```
will make "Bar" text render in hitpauses due to first block's ignorehitpause getting applied to the second block too (by mistake). This change attemps to fix this issue.
=> Fix IgnoreHitPause leaking to adjacent blocks in ZSS

data/guardbreak.zss
The characters now fall down from the air to the ground during the first state. This removes the need for the timer map and makes the animation transition look smoother.
=> Improved air to ground transition

src/bytecode.go, src/char.go, src/font.go
AttachedChars now can render text with their own fonts, since font selection in `Text` SCTRL is now done at a new CharGlobalInfo field for fonts.
Also, a bug regarding `color` parameter from `Text` SCTRL was addressed, where color was not getting set to default values properly, leading to Sprite-based fonts appearing invisible.
=> Bugfixes: Text SCTRL default color values, AttachedChar font loading

data/common1.cns.zss
Mugen has long had an issue where characters who have just exited a hit state cannot block in the same frame, appearing to be in the idle state but actually being unable to act. Hitting them in that frame (correctly) counts as a combo, even.
These changes attempt to keep the gameplay intact, but now keeping the character in a get hit animation while they are unable to move, so that the screen reflects what is truly happening.
This inadvertently fixes issue #597 because the character no longer falsely goes through an idle state.
=> Fixed transition between get hit and idle states

data/common1.cns.zss
Reverting the previous change as it introduced one frame of delay when guarding attacks after exiting hit stun. While this could also be handled in the common states, I feel that it would be too convoluted. This issue may require a deeper solution.
=> Reversion of previous change

src/image.go
The cache keeps a copy of all SFF objects (not the actual sprite data) so that they can be immediately reused when the same file is loaded again. A reference count is kept so that the last GC’ed version of an SFF will cause the cached copy to be deleted, too.
=> Implement SFF caching

src/camera.go, src/char.go, src/stage.go
・地面の高さを決める記述でミスがあったので修正
・zoomdelta周辺の記述をちょっと整理
・ズームアウト時のBGレイヤーのY軸変動をdeltaとzoomdeltaで分けて調整
・ステージのscaleがzoffsetlinkに影響しないように修正
・着地ステートのtimeを修正#779
・SuperpauseのP2defmulが乗算になるように修正#752
・nochainIDを同じキャラの攻撃でのみ有効になるように修正#772
・hitdefのteamsideが有効になるように修正
=> 地面の高さを決める記述でミスがあったので修正

src/bytecode.go, src/char.go
・Reversaldefでもfall系の記述は反映させるようにした#783
・bindされるとposのtriggerに本来のものでなく1F先の情報が表示される仕様は奇妙なのでikemenversionが付いてると起きないようにした
・Hitdefが出てない状態でHitdefのteamsideが参照される場合があったのを修正
=> Reversaldefでもfall系の記述は反映させるようにした

src/bytecode.go, src/char.go, src/compiler_functions.go, src/system.go
・Zoomステコンにstageboundパラメータを追加
デフォルトは1
これを0にするとステージ端の限界を無視してズームするようになる
また、cameraboundが無効になる
・P2の敵情報がラウンド間でリセットされていなかったのを修正
=> Zoomステコンにstageboundパラメータを追加

src/bytecode.go, src/compiler.go, src/compiler_functions.go, src/system.go
This is a series of commits that attempt modify the bytecode compiler in order to expand the syntax in ZSS and bring it to more standard programming conventions. New statements were added, prominently loops and switches.
**New statements added:**
Switches:
```coffeescript
switch life {
case 1000:
text{text: "Your life is full"}
case 500; 250:
text{text: "Your life is in halves"}
case 100:
default:
text{text: "You cannot recover life"}
}
```
In switches, the cases can be in any order, including the default one. Cases can have more than one expression, and adding code inside them is optional, meaning, you can add cases where nothing happens. Switch can help make code more understandable, and it's a great tool to code AI in specific.
For loops:
```coffeescript
for i = 0; 20; 2 { …
```
=> ZSS expansion: For/While loops, Switches, Break/Continue controls

src/char.go, src/image.go, src/stage.go
・Hitdefのp2statenoでヒットがカウントされない場合があったのを修正 #810
・フルカラー画像で減算処理した際にPalfxのaddの反転が2重になる場合があったのを修正
・KOした相手をP2情報として残し続けていたのを修正
・hiresとyscaledeltaを使用したステージで視差に誤りが出ていたのを修正
=> Hitdefのp2statenoでヒットがカウントされない場合があったのを修正

external/script/main.lua, src/bytecode.go, src/char.go, src/compiler.go, src/compiler_functions.go, src/lifebar.go, src/main.go, src/resources/defaultConfig.json, src/script.go, src/system.go
This PR introduces a new feature called "CommonFx". Just like most of the other common files, CommonFx is a file array located in `config.json` for general resource  files that can be accessed by all characters in a match. In this case, CommonFx expects definition (.def) files containing information for a "FightFx" package, including .sff, .air and .snd files. A prefix and anim scale can be defined in an info section.
A package .def looks something like this:
```ini
; Example for a Mortal Kombat effects package 
[Info]
prefix = MK ; Obligatory
fx.scale = 1
[Files]
air = mk.air
sff = mk.sff
snd = mk.snd
```
This package can then be accessed by adding/changing the prefix in valid parameters (usually anim/sound ones) from SCTRLs in a character's code:
```coffeescript
playSnd{value: MK5,0} …
```
=> Add support for "CommonFx" files

src/input.go
This is a minor patch but it significantly reduces the number of calls to the input system on each frame.
=> Only call GetJoystickButtons() when querying a button, not an axis

data/common.const, src/bytecode.go
This option should not be applied to non-1.0 characters. This compatibility issue does not pertain to non-1.0 characters and can cause confusion. #566
=> Default.LegacyGameDistanceSpecの適用を1.0キャラ限定に

data/dizzy.zss, data/score.zss
- The dizzy flag is now set to 1 as soon as the dizzy bar reaches 0
- The dizzy birds are now called immediately after the character is dizzied to avoid confusion
- Added a flag to prevent the character from being dizzied twice in the same combo
- The dizzy birds circling effect now uses ModifyExplod
- Some states can now use alternative get hit animations if the character has them
- Minor changes so the code is easier to read and modify later on
- Things like the cooldown timer and duration of dizzy state are now closer to commercial games, although not meant to recreate any of them
- Dizzy code is processed even outside RoundState 2, to prevent some odd case scenarios
=> Default dizzy system tweaks

data/dizzy.zss
- Fixed calling animation "AnimAirFall_comingDown" (5060) even if it doesn't exist
- The cooldown time doesn't go down during the get up state (5120)
=> Fixed always calling one optional animation

data/dizzy.zss
- The "hit ground from fall" animation now takes into account the character's ground level constant, like the common1 file does
=> Ground level fix

src/char.go
This commit fixes binding explod position when binding helper is destroyed during ko slow
Testing kfm:
[kfm.zip](https://github.com/ikemen-engine/Ikemen-GO/files/10703894/kfm.zip)
Simply press F1 during the match to reproduce the problem.
=> Fix binding explod position

src/bytecode.go, src/compiler.go
standard trigger constants prefixed with OC_ has been grouped with OC_ex_ constants. Also OC_ex_ ones now follow alphabetical order. Math, redirections and vars still use the old convention. It's a cosmetic change for consistency sake only - should not affect anything.
=> OC_ex_ constants rearrangement

data/common.const, data/common1.cns.zss
- Fix the issue where some of the const settings in MUGEN 1.0 and later could not be loaded in common1.cns.zss even when set for winmugen characters.
- Change the state numbers in dizzy.zss, guardbreak.zss, and tag.zss to be less conflicting numbers with existing characters. #545
=> fix: common1 const compatibility with 1.0 chars, conflicting state numbers

src/bytecode.go, src/char.go
- fix helper remapPal during first frame of the match
Fixes #1058
- fix helper remapPal omitting source/dest and assignment to -1
Fixes #1001
=> fix: helper remapPal during first frame of the match, omitting source/dest and assignment to -1 (#1058, #1001)

data/common1.cns.zss
Eliminated one frame of animation lag when switching from high to low guard and vice-versa. No effect on gameplay.
=> fix: Fixed guarding animation lag

src/char.go
getHitVar(fall.envshake.phase), if not assigned a value via HitDef, defaulted to NaN, instead of 0.
fixes: #1070
=> fix: getHitVar(fall.envshake.phase) default value (#1070)

src/char.go
In mugen hittime and hitshaketime counts down even if movetype != H.
Fixes: #1034
=> fix: hittime, hitshaketime reset if movetype != H (#1034)

src/anim.go, src/common.go
In mugen, for anim and angle parameters, leaving the value unassigned only defaults to 0 when comma follows. There is also no restriction for setting scaling parameters to 0.
Fixes: #1065
=> fix: fix anim scale set to 0 and defaults (#1065)

src/char.go
targetLifeAdd sctrl no longer ignores super.lifetodizzypointsmul and super.lifetoredlifemul constants
fixes: #1010
=> fix: fix targetLifeAdd ignoring super.lifetodizzypointsmul and super.lifetoredlifemul (#1010)

src/bytecode.go
- fix afterImage redirectId to not affect source object
Fixes: #1015
- fix destroyself redirectId to not stop script execution if not run on self
Fixes: #1014
=> fix: fix redirectId in afterImage and destroySelf

src/bytecode.go, src/char.go
GetHitVars should only be updated the instant the characters get hit but gethitvar(animtype) returned up to date value, unlike mugen
Fixes #1063
=> fix: fix gethitvar(animtype) not returning the correct value from the start of HitDef

data/tag.zss, src/bytecode.go, src/char.go, src/compiler.go, src/compiler_functions.go, src/script.go
In order to implement new flags compiler has been expanded to support int64 values.
While asserted all players won't die from taking damage.
While asserted, makes the player AILevel and AILevelF triggers return 0
While asserted player won't die from taking cheap damage
While asserted player won't die from taking damage
**Note:** [ikemenVersion](Character-features/#def_info_ikemenversion) changes default behaviour of this flag
While asserted player won't be affected by HitDef velocity adjustments upon KO
=> feat: new assertSpecial flags: globalnoko, noailevel, noguardko; changed: noko, nokovelocity

src/bytecode.go
backedge, backedgebodydist, backedgedist, bottomedge, frontedge, frontedgebodydist, frontedgedist, leftedge, rightedge, stagebackedge, stagefrontedge, topedge
Fixes #1096
=> fix: no localcoord for redirected edge triggers

build/get.cmd, build/get.sh, go.mod, go.sum, src/sound.go, src/system.go
Switch the beep dependency to a more active fork
Fixes #58
Fixes #609
=> fix: OGG Files playing at 2x speed, OGG loop crash

src/char.go
destroyself時にbind相手が5050に飛ばないバグが再発していたのを修正 #194
=> fix: bind p2 not going to state 5050 on recurring destroyself

data/training.zss, external/script/menu.lua, external/script/motif.lua
- Dummy can now be set to recover automatically from a fall. This is currently achieved by making the dummy jam buttons when appropriate
- A common feature of training modes. Previously, players had to resort to external means to practice or debug using this feature
- Fall Recovery can be set to None, Ground, Air or Random
- Dummy mode (standing, crouching, etc) moved above guard mode in the menu for a more logical order
=> feat: add Fall Recovery option to the training dummy

data/common1.cns.zss
- This state is used in Mugen to simply make the character fall down to the ground and land. As such it now behaves the same way as it did there and does not alter the character's animation
=> fix: Simplified state 51

src/char.go
- fix(char): make CTRL settable through most of roundstate = 3
- fix(char): autoturn resetting anim 5/6 indefinitely
These two commits fix #1130. This fix is also related to #277.
=> fix(char): CTRL not being able to be set while roundstate = 3, autoturn resetting anim 5/6 indefinitely, players having control after being defeated

src/char.go
- Player pushing and screenbound upon KO works more like Mugen 1.1
- Single players are always pushable and screenbound
- Simul (and tag) players are pushable while alive, and screenbound while not in the KO state itself
=> fix(char): playerpush upon KO

data/functions.zss
- Prevents Reversal message from appearing after, for instance, a successful Kung Fu Blocking
=> fix: reversal message on some HitOverrides

go.mod, go.sum, src/sound.go
A .mid or .midi files can now be used as bgm. The requirement is to also ship a soundfont file in sound/soundfont.sf2. Until a better design is discussed, this location is hardcoded.
=> feat: add MIDI playback support (#12)

src/char.go
Addresses #1057
(I also got the alternative solution to work, but it caused retrocompatibility issues as most characters aren't allowed to use throws if P2MoveType = H)
=> fix: GetHitVars no longer reset while dizzy

src/bytecode.go, src/char.go, src/compiler.go, src/script.go
- Like Mugen, one could not read the character's fall.defence_up constant directly, having to reverse the fall.defence_mul formula to get it. It is now accessible
=> feat: add const(data.fall.defence_up) trigger

src/char.go
- Replicates the Mugen behavior of this sctrl
- Fixes being unable to reset HitFall during the Dizzy state
=> fix: HitFallSet now also works outside of MoveType = H

data/training.zss
- Adjusted automatic Fall Recovery triggers so that it will not make the training dummy tech throws
- Fixed Ikemenversion = 1 characters on P1's side being killable in training mode
- Setting the dummy to "far" will make it stay away a certain distance instead of always walking to the corner (only noticeable with zoom out)
- Dummy won't keep walking back against the corner when trying to stay away from the player
=> fix: small training dummy behavior adjustment

src/system.go
- Characters under the NoIntroReset AssertSpecial flag still receive control at the start of the fight. This makes its intended use case easier to apply as there is currently no method to detect the time at which a player should be given control
=> fix: ctrl is still given while under NoIntroReset

src/char.go, src/system.go
- Adjusted process priority so that most of the benefits of processing movetype I before H are kept, but also that a helper that is not attacking is never processed before its root
- Character positions are always reset when skipping the intros
=> fix: revised player processing priority

src/bytecode.go, src/compiler_functions.go, src/font.go
Fixes #1177 (discussion #1178)
Fixes #1124 (discussion #1125)
- character font defaults to the character's localcoord
- lifebar font defaults to the lifebar's localcoord
- debug font defaults to the screen's localcoord and respects the debug font scale (it should look the same as the debug text).
- a custom localcoord can be assigned using the new "localcoord" parameter. "localcoord = 320, 240" is equivalent to the previous implementation.
=> feat: text sctrl localcoord support

data/functions.zss, data/tag.zss
- Adjusted tag jumping in state so that team members don't all jump to the same position before doing their win poses
- Disabled Reversal message in custom states, for better compatibility with at least a few more characters
=> fix: tag and lifebar messages minor adjustment

src/char.go
- Like Mugen, a position offset is applied when a character is hit into the air while lying down, keeping them lower to the ground
- Fixes #1064
=> feat: offset when char is hit from floor to air

src/bytecode.go, src/char.go, src/system.go
- Made RoundState 4 detection closer to Mugen: it will only switch from 3 to 4 when every character is ready for it
- Removed ctrl flag limitation in roundstate 4 as it does not exist in Mugen
- Fixed Offset Sctrl not accounting for RedirectID localcoord
- Fixed the recently added down hit offset varying with screen aspect ratio
- Fixes #1110
=> fix: RoundState 4 and Offset

src/char.go
- ReversalDefs now also assign a "hitby" ID to their targets
- Invalid targets are now dropped during "action prepare" instead of after state -1
- Fixes #1191
- Fixes #1042
=> fix: ReversalDef binding

data/training.zss, src/bytecode.go, src/compiler.go, src/script.go
- Previously available in the source code but not accessible. Returns the number of (conventional) air jumps the character has performed
- Fixed the training dummy not being able to perform double jumps
=> feat: new AirJumpCount trigger

data/training.zss, src/char.go
- The "control over" period now expires when characters enter their win poses, as in Mugen
- Asserting PostRoundInput now allows characters to jump during round end
- Simplified training dummy jumping instructions. This makes them work with more characters in more situations
- Superpause "unhittable" parameter is now reflected in the debug hitbox display (fixes #1012)
=> fix: ctrl at round end

src/char.go, src/system.go
- Fixed NoInput flag preventing characters from autoturning
- Moved state 52 turning instructions together with the other states
=> fix: AutoTurn during NoInput

src/char.go, src/compiler.go
- Added State +1. This state functions like State -4, except that it is processed after the character's current state. This allows some checks that are not possible in negative states (implements #1187)
- Adjusted air jumping so that it is performed by pressing (not holding) up, as in Mugen. Thus removed obsolete air jump flag from the code
- CtrlOver is in effect after the win poses
- Moved getting up from lie down to the end of action run, to remove the leftover hack in action finish
=> feat: added State +1

data/dizzy.zss, src/char.go, src/compiler.go
- Fixed juggle points being interpreted as 0 if the juggle line is omitted from a Statedef. This eliminates many infinite combos in characters using Mugen's default juggle system (fixes #764)
- Fixed juggle point subtraction. Previously, if a move connected but did not knock down, the player's juggle points were reset. Now they are stored and are only reset when the target is knocked down
- Fixed State +1 crashing when used in the ZSS language
- If a character's dizzy points are brought down to zero without the character being dizzied (for instance in a custom state), the next hit will only dizzy if it's not a super move or if it specifically deals dizzy damage
=> fix: Statedefs defaulting to 0 juggle points

src/char.go
This fixes some of Mugen's longtime issues:
- Characters can now block or do basic actions in the same frame they return to an idle state
- If a character attacks while holding back, the first frame of the attack will no longer guard automatically because of a lingering guard flag
- Fixes #1069
To compensate for this change, legacy characters (without ikemenversion) now cause 1 extra frame of hittime on their opponents, thus keeping their frame data the same as before.
=> fix: basic actions processed after current state

data/dizzy.zss, src/bytecode.go, src/char.go, src/compiler_functions.go
- Implemented two new Hitdef parameters: sparkangle and guard.sparkangle. These allow setting the hitspark rotation directly from a Hitdef
- If a character's dizzy points are 0 and they are hit by a move that cannot dizzy, the dizzy points will be set to 1. Similar to using kill = 0 in LifeAdd
=> feat: spark rotation directly from Hitdef

src/char.go, src/system.go
- Ctrl is set to 0 after wait.time
- CtrlOver flag behavior changed. It no longer checks for which phase of the round end we are in, but rather it is toggled on when the previous point happens
- CtrlOver boolean in the source code renamed to InputOver, as it is more descriptive of what it actually does
- Refactor: disabling inputs after wait.time is more simple: the character is directly flagged with NoInput (unless PostRoundInput is active)
- Sending characters to their win/lose poses leaves ctrl the way it was instead of changing it to 1 (fixes #1210)
- A side effect of these changes is that the applications of the PostRoundInput flag have been reduced, as that is mostly the new default behavior (like Mugen). This flag can still be used to allow inputs just before the win poses
Other:
- …
=> fix: make round end closer to Mugen's behavior

src/char.go
- Enables setting "hitonce = 0" for throws
- Fixes compatbility with [this character](https://mugenguild.com/forum/topics/cage-mk2-beta-release-1-197739.0.html)
=> fix: HitOnce parameter not working for throws

src/char.go
- Fixed helpers being able to block even without keyctrl
- Regression in 377e9e9df8055686dbb5172702cbefc783699862
=> fix: regression in guarding

src/char.go
- Some adjustments and failsafes for when explods are bound for 0 or 1 frames
- Fixes #1217
- Fixes #1218
=> fix: Explod binding with 1 frame of duration

src/bytecode.go, src/char.go, src/compiler.go, src/script.go
- Allows setting the default channels for hitsounds, much like the constants for hitsparks
- Restored the ability to redirect the NoStandGuard, NoCrouchGuard and NoAirGuard flags
=> feat: hit and guardsound channels constants

src/char.go
- Restored a pre-existing temporary fix that changes a bindtime of 0 to 1
- Fixes #1236
=> fix: explod updating during postype Back

README.md
Building on Windows, Mac, and Linux were pointing to incorrect location, this pr fixes it.
=> docs: Update README.md for build-docs links

src/bytecode.go, src/char.go, src/compiler.go, src/script.go, src/stage.go, src/system.go
- Returns the current (absolute) amplitude of the active EnvShake effect. Mostly useful for interactive stages
- The EnvShake mul parameter is now only applied after each cycle of the shaking effect. This makes it so that values lower than 0.9 don't stop the effect almost immediately
- Refactored first attack code: now works based on player number instead of ID. This allows characters to be flagged with first attack if any of their helpers hit the opponent, thus making the trigger easier to use. Now checked when a character or helper enters Movetype H rather than upon move contact, for improved compatibility with counter grabs (Geese type), super armor, etc
- Explod facing is now updated to 1 by default if PosType is modified (fixes #1252)
=> feat: EnvShake trigger

src/bytecode.go, src/compiler.go, src/script.go
- Replaces previous EnvShake trigger
- Allows checking the (remaining) time, frequency and amplitude of the current EnvShake
- Used as EnvShakeVar(time), EnvShakeVar(freq) or EnvShakeVar(ampl)
=> feat: EnvShakeVar trigger

src/bytecode.go, src/char.go, src/compiler_functions.go
- Setting this parameter to 1 makes the Explod be removed if the character changes state
- Fix: If a character is KO'd, their get hit animation is now updated to "fall type"
- Fix: HitVelSet no longer requires the character to be in Movetype H to work (same as Mugen 1.1)
=> feat: Explod RemoveOnChangeState parameter

src/bytecode.go, src/char.go, src/compiler_functions.go
- animelem= elem_no (int)
Explod anim start elem.
- animelemlooped= bvalue (boolean)
Setting this parameter to 1 makes the Explod anim elem being looped. Defaults to 0
**Those parameters can be modified by ModifyExplod sctrl.**
=> feat: AnimElem and AnimElemLooped parameters for explods.

src/bytecode.go, src/char.go, src/compiler.go, src/script.go
- Added an exception to the code so that characters hit by a type = None attack are correctly assigned a ChainID. Fixes #1268
- Added new trigger for GetHitVar "type". Returns the value of either groundtype or airtype, depending on where the character was hit
=> fix: type None and ChainID

data/dizzy.zss, data/guardbreak.zss, src/char.go
A few changes to make it behave more like Mugen:
- The fall defence bonus now stacks every time the character hits the ground
- Lie down recovery time only counts down in state 5110
- Hitting a character that's in state 5101 with a sweep now correctly sends them to state 5070
- The limit on hitting a character off the ground now depends on how much recovery time the char has left rather than how many times they have been bounced
- The value of PrevStateno when the character is hit into a custom state is more accurate to Mugen
Also:
- Dizzy and guard points recovery is no longer affected by defense multipliers
=> fix: lying down get hit behavior

data/dizzy.zss, data/functions.zss, data/guardbreak.zss, src/char.go, src/system.go
- Landing from physics A is no longer a loop, thus preventing a game crash if the landing state is also set to physics A
- Extra hit velocity on KO is no longer applied to statetype L
- Adjusted the "input over" flag so that KO characters can now process inputs while the round is still ongoing
- Being KO by itself no longer prevents the character from performing basic actions
- Adjusted PostRoundInput flag to enable inputs in more instances such as KO
- Adjusted "Technical" message so it does not give duplicate messages for some characters
- Minor adjustments and bug fixes to how guard points are recovered
- Every character now recovers them at the same rate, regardless of their maximum guard points. Recovery also happens every frame, including hitpause
- Minor refactor: dizzy and guard …
=> fix: landing, KO velocity and inputs, guard points

src/bytecode.go, src/char.go, src/compiler.go, src/compiler_functions.go
This rewrite attempts to fix almost all explod behavior inconsistencies regarding MUGEN 1.1. Only two behaviors haven't been reproduced (yet):
- Explod facing bug (facing works differently depending on player original facing, and remains the same when changing certain postypes. I don't think this bug is worth porting)
- Spawning explods with space = screen and postype = p1/p2 in a zoomed out stage doesn't place the explods in the proper position compared to MUGEN 1.1 (this might be worth looking out in the future).
This rewrite isn't feature expansion friendly, so code refactor might be needed in the future.
=> fix: rewrite Explod code to improve compatibility with MUGEN 1.1

data/common.const, data/tag.zss, data/training.zss, external/script/global.lua, src/char.go, src/lifebar.go, src/system.go
- Dizzy and guard points damage now works closer to regular life damage. Use positive values in a Hitdef to deal damage to the opponent and negative values to heal them
- Red life now works more like commercial games: it mirrors life rather than being appended to it. Meaning red life starts at LifeMax and decreases when the character gets hit
- During tag, partners now recover life only while they are in the waiting state, rather than the whole time they are standing by
- See #918
=> refactor: dizzy, guard, red life points

src/bytecode.go, src/char.go, src/compiler_functions.go
- Facing bug (sprite indefinitely facing left after it gets to face left for the first time) was finally properly recreated for non-ikemen characters.
- Non-ikemen characters can't influence in facing, pos, vel and accel values when not declaring postype anymore. This was notorious when, for example, creating an explod, then modifying its pos through ModifyExplod, and after that, calling ModifyExplod again to change postype without modifying anything else. Explod would inherit a relative pos value from prevous ModifyExplod call, when it shouldn't be like that.
A basic limitation lift was applied to Ikemen chars, so they can modify things like pos, vel, accel or facing even when not declaring postype. More explod behavior rework will be done in the future for Ikemenver characters.
=> fix: make ModifyExplod updating more like MUGEN

data/dizzy.zss
- Ajusted the conditions under which attacks can prevent a character from being dizzied. The previous code interfered with being dizzied by some throws
=> fix: dizzy prevention during throws

src/bytecode.go, src/char.go, src/compiler.go, src/script.go
- Now return 0 when a character is at the respective end of the stage
- Added "dist" to the trigger names. The previous trigger names are still accepted but deprecated
- See #1151
=> refactor: StageBackEdgeDist and StageFrontEdgeDist

src/camera.go, src/stage.go
Camera was getting stuck in a case where floortension was defined and the game had an aspect ratio different from 4:3. The game would try to compensate by modifying drawOffsetY, and this would affect camera BoundLo value. With floortension being defined, the camera would be pushed down by drawOffsetY, potentially creating this stuck effect. Stage initial Y position might be misaligned, though, though it might just be differences in aspect ratio. And tensionhigh/tensionlow behavior needs to be investigated further, since this change might directly affect it.
Also, a bg miscalculation was commented out, since it provoked behavior different from MUGEN 1.1
Thanks to @NeatUnsou for input regarding how to fix ydelta.
Fixes #1319
=> fix: BG yDelta scrolling speed, camera getting stuck in non-4:3 ratios

src/render_gl.go, src/shaders/ident.frag.glsl, src/shaders/ident.vert.glsl, src/shaders/sprite.frag.glsl, src/shaders/sprite.vert.glsl
See: https://github.com/ikemen-engine/Ikemen-GO/issues/1062#issuecomment-1640705487
An additional check was added for possible WebGL builds. I can't test it because I don't know to create a WASM build.
Fixes #728, #1062
=> fix: OS X systems not being able to compile GLSL shaders

src/sound.go
From my perception, reducing resampling quality doesn't noticeably affect the sound quality while improving overall game performance by a lot when sounds have to be processed.
=> perf: lock/unlock the speaker only if the music is going to be paused/unpaused, reduce resampling quality

data/training.zss, external/script/global.lua, src/char.go
- Previously, 1 extra frame of hit time was added for compatibility with Mugen characters. This frame is only necessary when a move hits, so it was now disabled when a move is guarded
- F2 now also removes red life (needed since the refactor)
- Training dummy adjustments
=> fix: guard frame advantage

data/score.zss
- Since first attack was refactored to work based on player number instead of ID, every time a new helper was spawned the player would get another first attack bonus. As such first attack score code is now only run by the root characters
=> fix: disabled repeating first attack score bonus

src/char.go
- In Mugen, placing + in a hitflag makes an attack connect only against opponents in movetype H, except if they are guarding. The last part was missing from Ikemen, creating unblockable setups that should not be possible
=> fix: HitFlag + and guarding

src/compiler.go, src/sound.go
Corrupted sounds are now just disabled when they can't be played due to data corruption. The engine exports a warning message at file load if a sound can't be played.
Fixes #1286 
Fixes #1325
=> fix: corrupted sounds freezing the game, ignorehitpause not affecting "else" statement in ZSS

src/system.go
- The ingame menu was previously drawn before the fade effects, so opening it during a fade made it unreadable
=> fix: game menu during fade

src/char.go
- Adjusted damage computation so that it rounds to the nearest integer, like Mugen, instead of always rounding up
=> fix: damage rounding method

src/char.go
- Adjusted projectiles so that they can hit even after their removetime expires, as in Mugen
- Fixes #1362
=> fix: projectiles not hitting after removetime expires

src/char.go
- Setting destination to -1 makes it take the same values as source
- Setting both destination and source to -1 clears all remaps
- Fixes #1382
- Reverted one line of code in the Hitdef priority check
- Fixes #1410
=> fix: RemapPal and Hitdef priority

src/char.go
- Helpers can now receive more damage than the life they have left
- Fixes #1413
=> fix: Helper damage limits

src/sound.go
The original implementation of tick() is not checking whether the sound is looping.
Fix #1417
=> fix: fix sounds with loop = 1 looping forever

src/bytecode.go, src/char.go, src/common.go, src/compiler_functions.go, src/image.go, src/render.go, src/render_gl.go, src/script.go, src/shaders/sprite.frag.glsl, src/stage.go
1. **Fixes related to this issues:**
Fixes #1411
Fixes #1373
Fixes #1326
Fixes #989
Fixes #288
Fixes #508
2.  **Fix: PalfFX mul values inverse bug if Trans sctrl blend = sub**
- **Feat:** Added new **invertblend** parameter for PalFx and AllPalFx (For BgPalFx mugen 1.1 behavior forced). It inverts current blend mode if enabled so **Sub** becomes **Add** and **Add** becomes **Sub**
- **For PalFx it accepts 4 values:**
- **0   = Disabled(mugen 1.0 blending behavior)**
- **1   = Enabled(mugen 1.0 blending behavior)**
- **-1  = Disabled(mugen 1.1 blending behavior)**
- **2    = Enabled(mugen 1.1 blending behavior)**
If character mugenversion is 1.1 and invertall = 1 and if invertblend param is ommited it inverts blend by default. For all other mugenversion invertblend = 0 if ommitted.
- **For …
=> fix: PalFx and Blending fixes

src/char.go
This PR fixes "Vs Style Debuts" Dudley's Rocket Uppercut hyper combo bug, as seen in the Discord server:
https://discord.com/channels/233345562261323776/233363722934943744/1162169367816060928
=> fix: Clamp AnimNo to 0 if its value is below zero (like MUGEN)

data/dizzy.zss, src/char.go, src/lifebar.go, src/system.go
Also, negative anim handling was improved to fix some dizzy system issues.
BREAKING CHANGE:
"No-sprite" anim used to be "-2", but now it's "-1".
=> fix: crash when not declaring anim/sprite files on char, move "no-sprite" anim from -2 to -1

data/dizzy.zss, src/bytecode.go, src/char.go, src/script.go
Anim No. negative values are now being handled like this:
- In ChangeAnim/ChangeAnim2 SCTRL: Any negative value (except for -2) is clamped to 0
- In ChangeState/SelfState SCTRL: Any negative value (except for -1 and -2) is clamped to 0
- In StateDef: Any negative value (except for -1 and -2) throws a warning message in the console
This is the best approach to mixing MUGEN 1.1 handling of negative values and Ikemen GO's -2 anim (which is a 'no-sprite' anim).
=> fix: Refine anim no. handling from #1448, PlayBGM SCTRL leaking to the character select screen

src/char.go
- In Mugen, projectiles aren't counted once their conditions for removal are met
- Fixes partial regression caused by #1405. Together with it, projectiles should be more accurate
- Fixes #1463
- Fixed a loophole in the code that prevented red life regeneration from being disabled correctly
- Fixes #1466
=> fix: projectile tallying and disabling red life

src/lifebar.go
This PR adds a new parameter to [Turns Face], `p<n>.teammate.ko.hide`, to hide KO'd teammates' portraits. Behaves similarly to Capcom vs. SNK 2.
=> feat: lifebar face teammate.ko.hide

src/bytecode.go, src/char.go, src/compiler.go, src/script.go
New Math triggers:
- Clamp(x,min,max) (float)
Return a value clamped to an inclusive range of two specified numbers
- Sign(value) (int)
Returns the sign of a real number. If value < 0 return -1. If value 0 return 0. if value > 0 return 1.
- Atan2(x,y) (float)
Returns the arc tangent of the two numbers x and y.
- Rad(value) (float)
Converts degress to radians.
- Deg(value) (float)
Converts radians to degress.
- Lerp(a,b,amount) (float)
Linear interpolation between two values.
New Char triggers:
- Angle (float)
Gets the value of the player's angle.
Example: "trigger1 = angle < 90" 
- Scale (float) (Arguments  x, y) 
Gets the value of the player's scale.
Example: "trigger1 = scale x< 2 || scale y > 2" 
- OffSet (float) (Arguments  x, y) 
Gets the value of the player's offset.
Example: …
=> feat: new Math triggers (Clamp, Sign, Atan2, Rad, Deg, Lerp) and char triggers (Angle, Scale, OffSet, Alpha)
